# Autogenerated wrapper script for HeFFTe_jll for aarch64-linux-musl-cxx11-cuda+none-mpi+mpiabi
export libheffte

using CompilerSupportLibraries_jll
using FFTW_jll
using MPIABI_jll
JLLWrappers.@generate_wrapper_header("HeFFTe")
JLLWrappers.@declare_library_product(libheffte, "libheffte.so.2")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, FFTW_jll, MPIABI_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libheffte,
        "lib/libheffte.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
