# Autogenerated wrapper script for HeFFTe_jll for aarch64-linux-gnu-cxx11-cuda+none-mpi+mpitrampoline
export libheffte

using CompilerSupportLibraries_jll
using FFTW_jll
using MPItrampoline_jll
JLLWrappers.@generate_wrapper_header("HeFFTe")
JLLWrappers.@declare_library_product(libheffte, "libheffte.so.2")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, FFTW_jll, MPItrampoline_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libheffte,
        "lib/libheffte.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
