# Autogenerated wrapper script for HeFFTe_jll for x86_64-linux-gnu-cxx11-cuda+12.1-mpi+mpiabi
export libheffte

using CompilerSupportLibraries_jll
using FFTW_jll
using MPIABI_jll
using CUDA_Runtime_jll
using CUDA_Driver_jll
JLLWrappers.@generate_wrapper_header("HeFFTe")
JLLWrappers.@declare_library_product(libheffte, "libheffte.so.2")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, FFTW_jll, MPIABI_jll, MPIPreferences, CUDA_Runtime_jll, CUDA_Driver_jll)
    JLLWrappers.@init_library_product(
        libheffte,
        "lib/libheffte.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
